routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::get('/dashboard', 'HomeController@index');

/*===============   Admin    ===================*/
Route::resource('user' ,'UserController');
Route::get('change-status/{id}', 'UserController@change_status');
Route::post('change-pass', 'UserController@change_pass');

/*===============   Member   ===================*/
Route::resource('member' ,'MemberController');

/*===============   Cash In   ===================*/
Route::get('cash-in', 'CashInController@index');
Route::get('cash-in/create', 'CashInController@create');
Route::post('cash-in/store', 'CashInController@store');

/*===============   Cash Out   ===================*/
Route::get('cash-out', 'CashOutController@index');
Route::get('cash-out/create', 'CashOutController@create');
Route::post('cash-out/store', 'CashOutController@store');

/*===============   Reports   ===================*/
Route::get('/reports/create', 'ReportController@create');
Route::post('reports', 'ReportController@index');
Route::post('reports-pdf', 'ReportController@reports_pdf');

/*===============   Investments   ===================*/
Route::get('/investments', 'InvestmentController@index');
Route::get('/investments/create', 'InvestmentController@create');
Route::post('/investments/store', 'InvestmentController@store');

/*===============   Bank Balance   ===================*/
Route::get('/bank-balance', 'BankBalanceController@index');
Route::get('/bank-balance/edit', 'BankBalanceController@edit');
Route::post('/bank-balance/update', 'BankBalanceController@update');

app/Member.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function cash_in()
    {
    	return $this->hasMany(CashIn::class);
    }    

    public function cash_out()
    {
    	return $this->hasMany(CashOut::class);
    }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use App\CashIn;
use App\CashOut;
use App\Member;
use App\User;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class MemberController extends Controller
{
    public function index()
    {   
    	$members = Member::all();
    	return view('members.index', compact('members'));
    }

    public function create()
    {	
    	return view('members.create');
    }

    public function store(Request $request)
    {	
    	$request->validate([
    	    'password' => 'required|min:8',
    	    'name' => 'required',
    	    'dob' => 'required',
    	    'nid' => 'required',
    	    'gender' => 'required',
    	    'phone' => 'required|unique:members',
    	    'email' => 'required|unique:users',
    	]);

    	$user = new User;
    	$user->name = $request->name;
    	$user->email = $request->email;
    	$user->password = Hash::make($request->password);
    	$user->user_role = 2;
    	$user->status = 1;
    	$user->save();

    	$user_id = User::where('email', $request->email)->first();

    	$member = new Member;
    	$member->name = $request->name;
    	$member->user_id = $user_id->id;
    	$member->gender = $request->gender;
    	$member->dob = $request->dob;
    	$member->father = $request->father;
    	$member->mother = $request->mother;
    	$member->nid = $request->nid;
    	$member->phone = $request->phone;
    	$member->present_addr = $request->present_addr;
    	$member->permanent_addr = $request->permanent_addr;
    	$member->spouse = $request->spouse;
        $member->spouse_nid = $request->spouse_nid;

    	if($request->hasFile('photo'))
    	{
    	    $image = $request->photo;
    	    $ext = $image->extension();
    	    $filename = uniqid().'.'.$ext;
    	    $image->storeAs('public',$filename);
    	    $member->photo = $filename;
    	}
        if($request->hasFile('spouse_photo'))
        {
            $image = $request->spouse_photo;
            $ext = $image->extension();
            $filename = uniqid().'.'.$ext;
            $image->storeAs('public/nominee',$filename);
            $member->spouse_photo = $filename;
        }

    	$member->save();

    	return redirect()->back()->with('msg', 'Member Added!');
    }

    public function show($id)
    {  
        $member = Member::find($id);
        $member_cash_in = CashIn::where('member_id', $id)->sum('total_credit');
        $member_cash_out = CashOut::where('member_id', $id)->sum('total_debit');
        return view('members.show', compact('member', 'member_cash_in', 'member_cash_out'));
    }

    public function edit($id)
    {   
        $member = Member::find($id);
        return view('members.edit', compact('member'));
    }

    public function update(Request $request, $id)
    {   
        $member = Member::find($id);

        $request->validate([
            'name' => 'required',
            'dob' => 'required',
            'nid' => 'required',
            'gender' => 'required',
            'phone' => 'required',
            'email' => 'required',
        ]);

        $user = User::find($request->user_id);
        $user->update([ 'email' => $request->email, 'name' => $request->name ]);

        $member = Member::find($id);
        $member->name = $request->name;
        $member->gender = $request->gender;
        $member->dob = $request->dob;
        $member->father = $request->father;
        $member->mother = $request->mother;
        $member->nid = $request->nid;
        $member->phone = $request->phone;
        $member->present_addr = $request->present_addr;
        $member->permanent_addr = $request->permanent_addr;
        $member->spouse = $request->spouse;
        $member->spouse_nid = $request->spouse_nid;
        $member->save();

        return redirect()->route('member.index')->with('msg', 'Update Successful!');
    }
}

resources/views/members/create.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success!</h4>
            {{ session('msg') }}
        </div>
@endif
@if ($errors->any())
	<div class="alert alert-danger alert-dismissible notify">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	    <h4><i class="icon fa fa-warning"></i>Error!</h4>
	    @foreach ($errors->all() as $error){{ $error }}@endforeach
	</div>
@endif

<div class="box">
    <div class="box-header" style="text-align: center;">
        <h1 class="box-title">Add Member</h1>
    </div>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
	    	<div class="box">
	       		<div class="box-body">
					<form action="{{ route('member.store') }}" method="POST" enctype="multipart/form-data">
						@csrf
						<div class="box-body">
							{{-- name --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="name" style="float: right;">Name :</label> </div>
								<div class="col-md-5">
									<input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Enter Name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>
							
							{{-- email --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="email" style="float: right;">Email :</label> </div>
								<div class="col-md-5">
									<input type="email" name="email" value="{{ old('email') }}" class="form-control" placeholder="Enter Email" required="">
								</div>
								<div class="col-md-3"></div>
							</div>
							
							{{-- password --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="password" style="float: right;">Password :</label> </div>
								<div class="col-md-5">
									<input type="password" name="password" value="{{ old('password') }}" class="form-control" placeholder="Enter Password" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- gender --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="gender" style="float: right;">Gender :</label> </div>
								<div class="col-md-5">
									<select name="gender" class="form-control">
										<option value="	">Select</option>
										<option value="male">Male</option>
										<option value="female">Female</option>
									</select>
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- DOB --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="dob" style="float: right;">Date of Birth :</label> </div>
								<div class="col-md-5">
									<input type="date" name="dob" value="{{ old('dob') }}" class="form-control" placeholder="Enter Date of Birth" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- father --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="father" style="float: right;">Father :</label> </div>
								<div class="col-md-5">
									<input type="text" name="father" value="{{ old('father') }}" class="form-control" placeholder="Enter father's name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- mother --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="mother" style="float: right;">Mother :</label> </div>
								<div class="col-md-5">
									<input type="text" name="mother" value="{{ old('mother') }}" class="form-control" placeholder="Enter mother's name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- NID --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="nid" style="float: right;">National ID Card(NID) :</label> </div>
								<div class="col-md-5">
									<input type="text" name="nid" value="{{ old('nid') }}" class="form-control" placeholder="Enter NID Number" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- phone --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="phone" style="float: right;">Phone Number :</label> </div>
								<div class="col-md-5">
									<input type="text" name="phone" value="{{ old('phone') }}" class="form-control" placeholder="Enter Phone Number" required="">
								</div>
								<div class="col-md-3"></div>
							</div>
							
							{{-- present address --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="present_addr" style="float: right;">Present Address :</label> </div>
								<div class="col-md-5">
									<textarea name="present_addr" class="form-control" placeholder="Enter Present Address" required="">{{ old('present_addr') }}</textarea> 
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- permanent address --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="permanent_addr" style="float: right;">Permanent Address :</label> </div>
								<div class="col-md-5">
									<textarea name="permanent_addr" class="form-control" placeholder="Enter Permanent Address" required="">{{ old('permanent_addr') }}</textarea> 
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- spouse --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="spouse" style="float: right;">Nominee Name :</label> </div>
								<div class="col-md-5">
									<input type="text" name="spouse" value="{{ old('spouse') }}" class="form-control" placeholder="Enter Name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- spouse nid --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="spouse_nid" style="float: right;">Nominee NID :</label> </div>
								<div class="col-md-5">
									<input type="number" name="spouse_nid" class="form-control" value="{{ old('spouse_nid') }}" placeholder="Enter NID" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- spouse photo --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="spouse_photo" style="float: right;">Nominee Photo :</label> </div>
								<div class="col-md-5">
									<input type="file" name="spouse_photo" class="form-control custom-file-input">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- photo --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="photo" style="float: right;">Photo :</label> </div>
								<div class="col-md-5">
									<input type="file" name="photo" class="form-control custom-file-input">
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
						<!-- /.box-body -->

						<div class="box-footer">
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"></div>
								<div class="col-md-5">
									<button type="submit" class="btn btn-success btn-block">Submit</button>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>	
				
				</form>
	       		</div>
	      	</div>
	      
	    </div>
    </div>
</section>

</div>

@endsection

resources/views/members/edit.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success!</h4>
            {{ session('msg') }}
        </div>
@endif
@if ($errors->any())
	<div class="alert alert-danger alert-dismissible notify">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	    <h4><i class="icon fa fa-warning"></i>Error!</h4>
	    @foreach ($errors->all() as $error){{ $error }}@endforeach
	</div>
@endif

<div class="box">
    <div class="box-header" style="text-align: center;">
        <h1 class="box-title">Update Member</h1>
    </div>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
	    	<div class="box">
	       		<div class="box-body">
					<form action="{{ route('member.update', $member->id) }}" method="POST" enctype="multipart/form-data">
						@csrf
						@method('PUT')
						<input type="hidden" name="user_id" value="{{ $member->user_id }}">
						<div class="box-body">
							{{-- name --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="name" style="float: right;">Name :</label> </div>
								<div class="col-md-5">
									<input type="text" name="name" value="{{ $member->name }}" class="form-control" placeholder="Enter Name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>
							
							{{-- email --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="email" style="float: right;">Email :</label> </div>
								<div class="col-md-5">
									<input type="email" name="email" value="{{ $member->user->email }}" class="form-control" placeholder="Enter Email" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- gender --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="gender" style="float: right;">Select :</label> </div>
								<div class="col-md-5">
									<select name="gender" class="form-control">
										<option value="male" {{ $member->gender == 'male' ? 'selected' : '' }}>Male</option>
										<option value="female" {{ $member->gender == 'female' ? 'selected' : '' }}>Female</option>
									</select>
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- DOB --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="dob" style="float: right;">Date of Birth :</label> </div>
								<div class="col-md-5">
									<input type="date" name="dob" value="{{ $member->dob }}" class="form-control" placeholder="Enter Date of Birth" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- father --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="father" style="float: right;">Father :</label> </div>
								<div class="col-md-5">
									<input type="text" name="father" value="{{ $member->father }}" class="form-control" placeholder="Enter father's name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- mother --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="mother" style="float: right;">Mother :</label> </div>
								<div class="col-md-5">
									<input type="text" name="mother" value="{{ $member->mother }}" class="form-control" placeholder="Enter mother's name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- NID --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="nid" style="float: right;">National ID Card(NID) :</label> </div>
								<div class="col-md-5">
									<input type="text" name="nid" value="{{ $member->nid }}" class="form-control" placeholder="Enter NID Number" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- phone --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="phone" style="float: right;">Phone Number :</label> </div>
								<div class="col-md-5">
									<input type="text" name="phone" value="{{ $member->phone }}" class="form-control" placeholder="Enter Phone Number" required="">
								</div>
								<div class="col-md-3"></div>
							</div>
							
							{{-- present address --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="present_addr" style="float: right;">Present Address :</label> </div>
								<div class="col-md-5">
									<textarea name="present_addr" class="form-control" placeholder="Enter Present Address" required="">{{ $member->present_addr }}</textarea> 
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- permanent address --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="permanent_addr" style="float: right;">Permanent Address :</label> </div>
								<div class="col-md-5">
									<textarea name="permanent_addr" class="form-control" placeholder="Enter Permanent Address" required="">{{ $member->permanent_addr }}</textarea> 
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- spouse --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="spouse" style="float: right;">Nominee Name :</label> </div>
								<div class="col-md-5">
									<input type="text" name="spouse" value="{{ $member->spouse }}" class="form-control" placeholder="Enter Name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							{{-- spouse nid --}}
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"> <label for="spouse" style="float: right;">Nominee NID :</label> </div>
								<div class="col-md-5">
									<input type="number" name="spouse_nid" value="{{ $member->spouse_nid }}" class="form-control" placeholder="Enter NID" required="">
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
						<!-- /.box-body -->

						<div class="box-footer">
							<div class="form-group row">
								<div class="col-md-2"></div>
								<div class="col-md-2"></div>
								<div class="col-md-5">
									<button type="submit" class="btn btn-success btn-block">Update</button>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>	
				
				</form>
	       		</div>
	      	</div>
	      
	    </div>
    </div>
</section>

</div>

@endsection

resources/views/members/index.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success!</h4>
            {{ session('msg') }}
        </div>
@endif
@if ($errors->any())
	<div class="alert alert-danger alert-dismissible notify">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	    <h4><i class="icon fa fa-warning"></i>Error!</h4>
	    @foreach ($errors->all() as $error){{ $error }}@endforeach
	</div>
@endif

<div class="box">
    <div class="box-header">
        <h1 class="box-title">Member List</h1>
    </div>

<section class="content">
    <div class="row">
            <div class="col-xs-12">
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-hover dataTable text-center" role="grid" aria-describedby="example1_info">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Photo</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Member From</th>
                            <th>Phone</th>
                            @if(Auth::user()->user_role == 1)
                                <th>Status</th>
                                <th>Change Password</th>
                            @endif
                            <th>Action</th>

                        </tr>
                    </thead>
                            
                    <tbody>
                    	@php $i = 0 @endphp
                        @foreach($members as $member)
                        <tr>
                        	<td>{{ $member->id }}</td>
                        	<td>
                        		<img class="img-circle" src="{{ asset('storage/'.$member->photo) }}" style="width: 50px;" alt="member_image">
                        	</td>
                        	<td>{{ $member->name }}</td>
                        	<td>{{ $member->user->email }}</td>
                        	<td>{{ Carbon\Carbon::parse($member->created_at)->format('Y-m-d') }}</td>
                        	<td>{{ $member->phone }}</td>
                            @if(Auth::user()->user_role == 1)
                            	<td>
                            		{{ $member->user->status == 1 ? 'Active' : 'Inactive' }}
                            		<span>
                            			<a href="/change-status/{{$member->user_id}}" class="btn btn-warning btn-sm">Change</a>
                            		</span>
                            	</td>
                        	    <td>
                            		<form action="/change-pass" method="post" class="form-group">
                            			@csrf
                            			<input onmouseover="type = 'text'" onmouseout="type = 'password';" type="password" name="password" class="form-control input-sm showPass" required>
                            			<input type="hidden" name="id" value="{{$member->user->id}}">
                            			<button type="submit" class="btn btn-danger btn-sm">Change</button>
                            		</form>  
                        	    </td>
                            @endif
                        	<td>
                                @if(Auth::user()->user_role == 1)
                                   <a href="{{ route('member.edit', $member->id) }}" title="Edit Profile">
                                        <i class="fa fa-pencil-square-o" style="font-size: 20px;"></i>
                                    </a> &nbsp; | &nbsp;
                                @endif

                                <a href="{{ route('member.show', $member->id) }}" title="View Profile">
                                    <i class="fa fa-user" style="font-size: 20px;"></i>
                                </a>
                        		
                        	</td>
                        </tr>
                        @php $i++ @endphp
                        @endforeach
                    </tbody>
                            
                </table>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
        </div>
</section>

</div>

@endsection

resources/views/members/show.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="box">
    <div class="box-header" style="text-align: center;" style="font-family: roboto slab">
        <h1 class="box-title">Member Profile</h1>
    </div>

<section class="content">
    <div class="box">
    	<div class="box-body">
			<div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-2">
					<img src="{{ asset('storage/'.$member->photo) }}" alt="member photo" style="width: 100%; height: 135px; border: 1px solid #222d32;">
				</div>
				<div class="col-md-2"></div>
				<div class="col-md-2"></div>
				<div class="col-md-2">
					<img src="{{ asset('storage/nominee/'.$member->spouse_photo) }}" alt="nominee photo" style="width: 100%; height: 135px; border: 1px solid #222d32;">
				</div>
				<div class="col-md-2"></div>
			</div><hr style="border: 1px solid #3c8dbc;"><br>
			<div class="row">
				<div class="col-md-6" style="border-right: 2px solid #3c8dbc;">
					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Member Name :</strong></div>
								<div class="col-md-5"><strong>{{ $member->name }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Member Phone :</strong></div>
								<div class="col-md-5"><strong>{{ $member->phone }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Member Email :</strong></div>
								<div class="col-md-5"><strong>{{ $member->user->email }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Gender :</strong></div>
								<div class="col-md-5"><strong>{{ $member->gender }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Date of Birth :</strong></div>
								<div class="col-md-5"><strong>{{ $member->dob }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>National ID :</strong></div>
								<div class="col-md-5"><strong>{{ $member->nid }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Status :</strong></div>
								<div class="col-md-5">
									<strong>{{ $member->user->status == 1 ? "ACTIVE" : "INACTIVE" }}</strong>
								</div>
								<div class="col-md-1"></div>
							</div><br>
							
							@if(Auth::user()->user_role == 1 || Auth::user()->id == $member->user_id)
								<div class="row">
									<div class="col-md-1"></div>
									<div class="col-md-5"><strong>Total Cash In :</strong></div>
									<div class="col-md-5">
										<strong>{{ $member_cash_in }}</strong>
									</div>
									<div class="col-md-1"></div>
								</div>
							@endif
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Nominee :</strong></div>
								<div class="col-md-5"><strong>{{ $member->spouse }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Nominee NID :</strong></div>
								<div class="col-md-5"><strong>{{ $member->spouse_nid }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Father Name :</strong></div>
								<div class="col-md-5"><strong>{{ $member->father }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Mother Name :</strong></div>
								<div class="col-md-5"><strong>{{ $member->mother }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Present Address :</strong></div>
								<div class="col-md-5"><strong>{{ $member->present_addr }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Permanent Address :</strong></div>
								<div class="col-md-5"><strong>{{ $member->permanent_addr }}</strong></div>
								<div class="col-md-1"></div>
							</div><br>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-5"><strong>Joining Date :</strong></div>
								<div class="col-md-5">
									<strong>{{ Carbon\Carbon::parse($member->created_at)->format('Y-m-d') }}</strong>
								</div>
								<div class="col-md-1"></div>
							</div><br>

							@if(Auth::user()->user_role == 1 || Auth::user()->id == $member->user_id)
								<div class="row">
									<div class="col-md-1"></div>
									<div class="col-md-5"><strong>Total Cash Out :</strong></div>
									<div class="col-md-5">
										<strong>{{ $member_cash_out }}</strong>
									</div>
									<div class="col-md-1"></div>
								</div>
							@endif
						</div>
					</div>
				</div>
			</div>
				
      	</div>
    </div>
</section>

</div>

@endsection