routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::get('/dashboard', 'HomeController@index');

/*===============   Admin    ===================*/
Route::resource('user' ,'UserController');
Route::get('change-status/{id}', 'UserController@change_status');
Route::post('change-pass', 'UserController@change_pass');

/*===============   Member   ===================*/
Route::resource('member' ,'MemberController');

/*===============   Cash In   ===================*/
Route::get('cash-in', 'CashInController@index');
Route::get('cash-in/create', 'CashInController@create');
Route::post('cash-in/store', 'CashInController@store');

/*===============   Cash Out   ===================*/
Route::get('cash-out', 'CashOutController@index');
Route::get('cash-out/create', 'CashOutController@create');
Route::post('cash-out/store', 'CashOutController@store');

/*===============   Reports   ===================*/
Route::get('/reports/create', 'ReportController@create');
Route::post('reports', 'ReportController@index');
Route::post('reports-pdf', 'ReportController@reports_pdf');

/*===============   Investments   ===================*/
Route::get('/investments', 'InvestmentController@index');
Route::get('/investments/create', 'InvestmentController@create');
Route::post('/investments/store', 'InvestmentController@store');

/*===============   Bank Balance   ===================*/
Route::get('/bank-balance', 'BankBalanceController@index');
Route::get('/bank-balance/edit', 'BankBalanceController@edit');
Route::post('/bank-balance/update', 'BankBalanceController@update');

app/User.php
<?php

namespace App;

use App\Member;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status', 'user_role',
    ];

    public function member()
    {
    	return $this->hasOnes(Member::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $users = User::where('user_role', 1)->get();
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'password' => 'required|min:8',
            'name' => 'required',
            'email' => 'required|unique:users',
        ]);
        
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->user_role = 1;
        $user->status = 1;
        $user->save();
        return redirect()->back()->with('msg', 'Admin Added!');
    }

    public function change_status($id)
    {
        $user = User::find($id);
        if ($user->status == 1) 
        {
            $user->update(['status' => 0]);
        }
        else
        {
            $user->update(['status' => 1]);
        }

        return redirect()->back()->with('msg', 'Status Changed!'); 
    }

    public function change_pass(Request $request)
    {
        $request->validate([
            'password' => 'required|min:8',
        ]);
        $user = User::find($request->id);
        $user->update(['password' => Hash::make($request->password)]);
        return redirect()->back()->with('msg', 'Password Changed!'); 
    }


}

resources/views/user/create.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success!</h4>
            {{ session('msg') }}
        </div>
@endif
@if ($errors->any())
	<div class="alert alert-danger alert-dismissible notify">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	    <h4><i class="icon fa fa-warning"></i>Error!</h4>
	    @foreach ($errors->all() as $error){{ $error }}@endforeach
	</div>
@endif

<div class="box">
    <div class="box-header" style="text-align: center;">
        <h1 class="box-title">Add an Admin</h1>
    </div>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
	    	<div class="box">
	       		<div class="box-body">
					<form role="form" method="post" action="{{ route('user.store') }}">
						@csrf
						<div class="box-body">

							<div class="form-group row">
								<div class="col-md-3"></div>
								<div class="col-md-1"> <label for="name">Name</label> </div>
								<div class="col-md-5">
									<input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Enter Name" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							<div class="form-group row">
								<div class="col-md-3"></div>
								<div class="col-md-1"> <label for="email">Email</label> </div>
								<div class="col-md-5">
									<input type="email" name="email" value="{{ old('email') }}" class="form-control" placeholder="Enter Email" required="">
								</div>
								<div class="col-md-3"></div>
							</div>

							<div class="form-group row">
								<div class="col-md-3"></div>
								<div class="col-md-1"> <label for="password">Password</label> </div>
								<div class="col-md-5">
									<input type="password" name="password" value="{{ old('password') }}" class="form-control" placeholder="Enter Password" required="">
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
						<!-- /.box-body -->
						<div class="box-footer">
							<div class="form-group row">
								<div class="col-md-3"></div>
								<div class="col-md-1"></div>
								<div class="col-md-5">
									<button type="submit" class="btn btn-success btn-block">Submit</button>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>	
				
				</form>
	       		</div>
	      	</div>
	      
	    </div>
    </div>
</section>

</div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success!</h4>
            {{ session('msg') }}
        </div>
@endif
@if ($errors->any())
	<div class="alert alert-danger alert-dismissible notify">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	    <h4><i class="icon fa fa-warning"></i>Error!</h4>
	    @foreach ($errors->all() as $error){{ $error }}@endforeach
	</div>
@endif

<div class="box">
    <div class="box-header">
        <h1 class="box-title">Admin List</h1>
    </div>

<section class="content">
    <div class="row">
            <div class="col-xs-12">
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-hover dataTable text-center" role="grid" aria-describedby="example1_info">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Change Password</th>

                        </tr>
                    </thead>
                            
                    <tbody>
                    	@php $i = 0 @endphp
                        @foreach($users as $user)
                        <tr>
                        	<td>{{ $user->id }}</td>
                        	<td>{{ $user->name }}</td>
                        	<td>{{ $user->email }}</td>
                        	<td>{{ $user->status == 1 ? 'Active' : 'Inactive' }}
                        		<span>
                        			<a href="/change-status/{{$user->id}}" class="btn btn-warning btn-sm">Change</a>
                        		</span>
                        	</td>
                        	<td>
                        		<form action="/change-pass" method="post" class="form-group">
                        			@csrf
                        			<input onmouseover="type = 'text'" onmouseout="type = 'password';" type="password" name="password" class="form-control input-sm showPass" required>
                        			<input type="hidden" name="id" value="{{$user->id}}">
                        			<button type="submit" class="btn btn-danger btn-sm">Change</button>
                        		</form>
                        	</td>
                        </tr>
                        @php $i++ @endphp
                        @endforeach
                    </tbody>
                            
                </table>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
        </div>
</section>

</div>

@endsection