routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::get('/dashboard', 'HomeController@index');

/*===============   Admin    ===================*/
Route::resource('user' ,'UserController');
Route::get('change-status/{id}', 'UserController@change_status');
Route::post('change-pass', 'UserController@change_pass');

/*===============   Member   ===================*/
Route::resource('member' ,'MemberController');

/*===============   Cash In   ===================*/
Route::get('cash-in', 'CashInController@index');
Route::get('cash-in/create', 'CashInController@create');
Route::post('cash-in/store', 'CashInController@store');

/*===============   Cash Out   ===================*/
Route::get('cash-out', 'CashOutController@index');
Route::get('cash-out/create', 'CashOutController@create');
Route::post('cash-out/store', 'CashOutController@store');

/*===============   Reports   ===================*/
Route::get('/reports/create', 'ReportController@create');
Route::post('reports', 'ReportController@index');
Route::post('reports-pdf', 'ReportController@reports_pdf');

/*===============   Investments   ===================*/
Route::get('/investments', 'InvestmentController@index');
Route::get('/investments/create', 'InvestmentController@create');
Route::post('/investments/store', 'InvestmentController@store');

/*===============   Bank Balance   ===================*/
Route::get('/bank-balance', 'BankBalanceController@index');
Route::get('/bank-balance/edit', 'BankBalanceController@edit');
Route::post('/bank-balance/update', 'BankBalanceController@update');

resources/views/includes/default_js.blade.php
<!--======================================= Common js STARTS =====================================-->

<!-- jQuery 3 -->
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('bower_components/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{ asset('bower_components/select2/dist/js/select2.full.min.js') }}"></script>


<!-- App js -->
<script src="{{asset('js/app.js')}}"></script>
<!-- Morris.js charts -->
<script src="{{asset('bower_components/raphael/raphael.min.js')}}"></script>
<script src="{{asset('bower_components/morris.js/morris.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('bower_components/jquery-sparkline/dist/jquery.sparkline.min.js')}}"></script>
<!-- jvectormap -->
<script src="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('bower_components/jquery-knob/dist/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('bower_components/moment/min/moment.min.js')}}"></script>
<script src="{{asset('bower_components/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<!-- datepicker -->
<script src="{{asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
<!-- Slimscroll -->
<script src="{{asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<!-- FastClick -->
<script src="{{asset('bower_components/fastclick/lib/fastclick.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('dist/js/pages/dashboard.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('dist/js/demo.js')}}"></script>

<!-- DataTables -->
<script src="{{asset('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>

</script>

<script type="text/javascript">
    $("#example1").DataTable();
    $("#example2").DataTable();
    $("#example3").DataTable();
	$("#example5").DataTable();
    var usedNames = [];
$("#month option").val(function(idx, val) {
  $(this).siblings('[value="'+ val +'"]').remove();
});
    $.fn.datepicker.defaults.format = "yyyy-mm-dd";
	$('.datepicker').datepicker({
    	autoclose: true
    });
    $(".alert.notify").fadeIn(2000,function(){
    	setTimeout(function() {
    		$(".alert.notify").fadeOut(1000);    		
    	}, 5000);
    });
    $('ul.nav-tabs li a').click(function(){
    	$('.tab-pane').removeClass('show');
    });
    

</script>



<!--======================================= Common js ENDS =======================================-->

resources/views/includes/footer.blade.php
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
    <strong>Copyright &copy; Meghna Development Society </strong>
  </footer>

resources/views/includes/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="{{ url('/dashboard') }}" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini" style="font-size: 80% !important;">Meghna Development Society</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Meghna Development Society</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{ asset('img/profile.png') }}" class="user-image" alt="User Image">
            <span class="hidden-xs">{{ Auth::user()->name }}</span>
          </a>
                  

          <ul class="dropdown-menu" style="border: 1px solid #3c8dbc;">
            <!-- User image -->
            <li class="user-header">

              <img src="{{ asset('img/profile.png') }}" class="img-circle" alt="User Image">

              <p>
                {{ Auth::user()->name }} -
                @if(Auth::user()->user_role == 1) {{ 'Admin' }} @endif
                <small>Member since {{ substr(Auth::user()->created_at,0,10) }}</small>
              </p>
            </li>
            
            <!-- Menu Footer-->
            <li class="user-footer">
              <!-- <div class="pull-left">
                <a href="#" class="btn btn-primary btn-flat">Profile</a>
              </div> -->
              <div class="pull-right">
                <a href="{{ '/logout' }}" class="btn btn-primary btn-flat">Logout</a>
              </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/includes/html_head.blade.php
<!--========================HTML HEAD STARTS========================-->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>DMS | Dashboard</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<meta name="csrf-token" content="{{ csrf_token() }}">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{asset('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('bower_components/font-awesome/css/font-awesome.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{asset('bower_components/Ionicons/css/ionicons.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('dist/css/AdminLTE.min.css')}}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{asset('dist/css/skins/_all-skins.min.css')}}">
<!-- Morris chart -->
<link rel="stylesheet" href="{{asset('bower_components/morris.js/morris.css')}}">
<!-- jvectormap -->
<link rel="stylesheet" href="{{asset('bower_components/jvectormap/jquery-jvectormap.css')}}">
<!-- Select2 -->
  <link rel="stylesheet" href="{{ asset('bower_components/select2/dist/css/select2.min.css') }}">
<!-- Date Picker -->
<link rel="stylesheet" href="{{asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{asset('bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  @yield('stylesheets')
<!--========================HTML HEAD ENDS========================-->

resources/views/includes/main_menu.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{ asset('img/profile.png') }}" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>{{ Auth::user()->name }}</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MAIN MENU</li>
      
      {{-- Dashboard --}}
      <li class="treeview">
        <li>
          <a href="{{ url('/dashboard') }}">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
      </li>
  
  {{-- Admin --}}
  @if(Auth::user()->user_role == 1)
  <li class="treeview">
      <a href="{{ route('user.index') }}">
          <i class="fa fa-user"></i> <span>Admin</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
          <li>
              <a href="{{ route('user.index') }}"><i class="fa fa-circle-o"></i>Admin List</a>
          </li>
          <li>
              <a href="{{ route('user.create') }}"><i class="fa fa-circle-o"></i>Add Admin</a>
          </li>
      </ul>
  </li>
  @endif

  {{-- Member --}}
  <li class="treeview">
      <a href="{{ route('member.index') }}">
          <i class="fa fa-users"></i> <span>Member</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
          <li>
              <a href="{{ route('member.index') }}"><i class="fa fa-circle-o"></i>Member List</a>
          </li>
          @if(Auth::user()->user_role == 1)
            <li>
                <a href="{{ route('member.create') }}"><i class="fa fa-circle-o"></i>Add Member</a>
            </li>
          @endif
      </ul>
  </li>

  {{-- Cash In --}}
  <li class="treeview">
      <a href="{{ url('/cash-in') }}">
          <i class="fa fa-money"></i> <span>Cash In</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
          <li>
              <a href="{{ url('/cash-in') }}"><i class="fa fa-circle-o"></i>All Cash In</a>
          </li>
          @if(Auth::user()->user_role == 1)
            <li>
                <a href="{{ url('/cash-in/create') }}"><i class="fa fa-circle-o"></i>Add Cash In</a>
            </li>
          @endif
      </ul>
  </li>  

  {{-- Cash Out --}}
  <li class="treeview">
      <a href="{{ url('/cash-out') }}">
          <i class="fa fa-money"></i> <span>Cash Out</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
          <li>
              <a href="{{ url('/cash-out') }}"><i class="fa fa-circle-o"></i>All Cash Out</a>
          </li>
          @if(Auth::user()->user_role == 1)
            <li>
                <a href="{{ url('/cash-out/create') }}"><i class="fa fa-circle-o"></i>Add Cash Out</a>
            </li>
          @endif
      </ul>
  </li>

  {{-- Investments --}}
  <li class="treeview">
      <a href="{{ url('/investments') }}">
          <i class="fa fa-usd"></i> <span>Investment</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
          <li>
              <a href="{{ url('/investments') }}"><i class="fa fa-circle-o"></i>All Investment</a>
          </li>
          @if(Auth::user()->user_role == 1)
            <li>
                <a href="{{ url('/investments/create') }}"><i class="fa fa-circle-o"></i>Add Investment</a>
            </li>
          @endif
      </ul>
  </li>

  {{-- Reports --}}
  <li class="treeview">
    <li>
      <a href="{{ url('/reports/create') }}">
        <i class="fa fa-line-chart"></i> <span>Reports</span>
      </a>
    </li>
  </li> 

  {{-- Bank Balance --}}
  <li class="treeview">
    <li>
      <a href="{{ url('/bank-balance') }}">
        <i class="fa fa-line-chart"></i> <span>Bank Balance</span>
      </a>
    </li>
  </li> 

</section>
  <!-- /.sidebar -->

</aside>